### PR TITLE
injected query validation service

### PR DESCRIPTION
**Pull request by johibkhan2**

### CODE REVIEW

**Comment by ir73** [comment]
there also seems to be an inconsistency with `datasource-measures-wizard-step.component.spec.js` what step does this test represent?

**Comment by techkpi** [comment]
@johibkhan2 and @ir73 : Can this be merged? if not @johibkhan2 , can you please do the needful

**Comment by ir73** [comment]
I approved, so yes good to go from my side.

**Comment by techkpi** [comment]
> I approved, so yes good to go from my side.

Thanks @ir73

**Pull request merged**
